### PR TITLE
Add new logo

### PR DESCRIPTION
**Pull request by elalemanyo**
Do we need a logo? Most probably not, but... 😀

image

### CODE REVIEW

**Review by rstammer — APPROVED** [review]
I really like it 🎵 👍 :)

**Comment by elalemanyo** [comment]
@dansch @rstammer @UliKuch everybody happy?

**Review by UliKuch — APPROVED** [review]
Yes, the logo looks really great! ❤️

**Review by dansch — APPROVED** [review]
🎨 Pure art! Pretty happy 😄 - let's merge it in!

**Pull request merged**
